<?php

/***************************************************************************
 *   english.php                                                           *
 *   Yggdrasil: English Language File                                      *
 *                                                                         *
 *   Copyright (C) 2006-2011 by Leif B. Kristensen <leif@solumslekt.org>   *
 *   All rights reserved. For terms of use, see LICENSE.txt                *
 ***************************************************************************/

// note that every variable in this file starts with an underscore.
// this will facilitate reading of the source code, as well as
// avoiding variable naming conflicts.

$_lang = 'en';
$_AP20 = "kp"; // To test for ap20 extended functions; provides domain rectype (AP20 specific)
$_App_name = 'Yggdrasil/'.$dbname.' ver:1.0[55]';
$_Add = 'Add';
$_Add_link = 'Assert existence of a person from this source';
$_Edit_link = 'Edit mention of person';
$_Create_link = 'Assert existence of a person';
$_Name_in_the_source = 'Person name and contextual info as mentioned in the source';
$_Linkage_role = 'Role';
$_Surety = 'How sure?';
$_cited_by_source = 'cited by this source';
$_Add_child = 'Add child';
$_Add_child_with = 'Add child with';
$_Add_event = 'Add event';
$_Add_event_for = 'Add event for';
$_Add_person = 'Add person';
$_Add_source = 'Add source';
// sms . See source_manager.php 29 July 2011. Leave undefined or empty to not check for leaf sources before showing $_Add_source link.
$_No_Add_source_leaf = 'source type a leaf (no subsources).'; 
$_Add_spouse = 'Add spouse';
$_Add_unrelated = 'Add unrelated';
$_Adds_birth_event = 'Adds birth event';
$_after = 'after';
$_Age = 'Age';
$_All = 'All';
$_ancestors = 'ancestors';
$_and = 'and';
$_associated_with_this_source = 'associated with this source';
$_Associated_events = 'Events associated with this source';
$_Associated_relations = 'Relations associated with this source';
$_before = 'before';
$_between = 'between';
$_Birth_year = 'Birth year';
$_born = 'born';
$_Branch = 'Branch';
$_Cannot_Merge = 'Cannot merge';
$_Child = 'Children';
$_HasDescendantsLabel = 'Has descendants'; /* sms added for span title help on + symbol */
$_child = 'child';
$_Citations = 'Citations';
$_Clean = 'Mark as Cleaned';
$_ca = 'ca.';
$_Contents = 'Contents';
$_coparents = 'coparents';
$_Date = 'Date';
$_daughter = 'daughter';
$_delete = 'delete';
$_Delete_person = 'Delete person';
$_deletion_links = 'deletion links';
$_Descendants = 'Descendants';
$_descendants = 'descendants';
$_Died_young = 'Died young';
$_Different_fathers = 'The persons have different fathers';
$_Different_mothers = 'The persons have different mothers';
$_Differing_genders = 'The genders of the two persons are differing';
$_Differing_given_names = 'The given names of the two persons are differing';
$_Differing_birth_years = 'The birth years of the two persons are differing';
$_Differing_patronyms = 'The patronyms of the two persons are differing';
$_edit = 'edit';
$_Edit = 'Edit';
$_Edit_event = 'Edit event';
$_Edit_person = 'Edit person';
$_Edit_place_name = 'Edit place name';
$_Edit_source = 'Edit source';
$_Email_addr = 'E-mail address';
$_Epithet = 'ALT forename(s)';
$_exact = ' exact';
$_event_type = 'event type';
$_Event_types = 'Event types';
$_Event_note = 'Event note';
$_event = 'event';
$_events = 'events';
$_event_definition = 'event type definition';
$_Events = 'Events';
$_Event_Manager = 'Event Manager';
$_Family = 'Family';
$_family = 'family';
$_Father = 'Father';
$_father = 'father';
$_Female = 'Female';
$_Full = 'Full';
$_Full_name = 'Full name';
$_from_to = 'from-to';
$_Gender = 'Sex';
$_Given = 'Forename';
$_Given_name = 'Forename';
$_goto = 'go to';
$_Goto_person = 'Go to person';
$_Hide = 'Hide';
$_hits = 'hits';
$_Husband = 'Husband';
$_ID = 'ID number';
$_in_this_report = 'in this report';
$_Index_and_name_search = 'Index and name search';
$_Index = 'Search / Last 20';
$_Initials = 'Initials';
$_Insert = 'Insert';
$_insert = 'insert';
$_is = 'is';
$_Language = 'Language';
$_Last = 'Last';
$_last_edited = 'last edited';
$_Leaf = 'Leaf';
$_Level = 'Level';
$_Link_to_person = 'Link to person in the database';
$_Living = 'Living';
$_Male = 'Male';
$_Mark_as = 'Mark as';
$_Married = 'Married';
$_Mentioned_in_probate_after = 'Mentioned in probate after';
$_Merge = 'Merge';
$_Merge_persons = 'Merge persons';
$_Merge_persons_failed = 'Merge persons failed';
$_Mother = 'Mother';
$_mother = 'mother';
$_Name = 'Name';
$_Next = 'Next';
$_No = 'No';
$_Non_Clean = 'Mark as Not Cleaned';
$_Not_died_young = 'Not died young';
$_NslashA = 'N/A'; // N/A
$_Occupation = 'ALT surname(s)';
$_of = 'of';
$_off = 'off';
$_on = 'on';
$_or = 'or';
$_Other_children = 'Other children';
$_Parent_node = 'Parent node';
$_parent_node = 'parent node';
$_Partial = 'Partial';
$_Patronym = 'Maiden Name';
$_Pedigree = 'Pedigree';
$_Pedigree_for = 'Pedigree for';
$_person = 'person';
$_persons = 'persons';
$_Persons_Mentioned_In_Source = 'Persons mentioned in this source';
$_Mentioned_In_Source = 'Mentioned in source';
$_Place = 'Place';
$_Place_filter = 'Place filter';
$_Places = 'Places';
$_Place_names = 'Place names';
$_Previous = 'Previous';
$_Printed = 'Printed';
$_Private = 'Private';
$_Public = 'Public';
$_Reason = 'Reason';
$_References = 'References';
$_relation = 'relation';
$_Relations = 'Relations';
$_relations = 'relations';
$_report = 'report';
$_Return_to = 'Return to';
$_say = 'say';
$_Search = 'Search';
$_Search_for_couples = 'Search for couples';
$_Search_for_sources = 'Search for sources';
$_Search_result = 'Search result';
$_seconds = 's';
$_Select = 'Select';
$_select = 'select';
$_Show = 'Show';
$_son = 'son';
$_Sort_date = 'Sort date';
$_Sort_order = 'Sort order';
$_Source = 'Source';
$_Source_date = 'Source date';
$_Source_Manager = 'Source Manager';
$_source_type = 'source type';
$_Source_types = 'Source types';
$_Sources = 'Sources';
$_sources = 'sources';
$_source = 'source';
$_SP = 'SP'; // second principal (short form)
$_Spouse = 'Spouse';
$_spouse = 'spouse';
$_subsource = 'subsource';
$_Subsource = 'Subsource';
$_subsources = 'subsources';
$_Subsources = 'Subsources';
$_Subtype = 'Subtype';
$_Surname = 'Surname';
$_Text = 'Text';
$_The_last_50_edited = 'The 20 most recently edited';
$_There_are = 'There are';
$_This = 'This';
$_This_page_was_generated_in = 'generated in';
$_Time_zone = 'Time zone';
$_To = 'To';
$_to = 'to';
$_toolhelp_cit_delete = 'Delete the citation. This deletes the association between this event and the source referenced by the footnote; the source id is (%d). Note that deleting the citation deletes neither the referenced event nor the source itself.';
$_toolhelp_has_descendants = 'Child (%d) has descendants';
$_toolhelp_add_parent = 'Create a NEW person as the %s of this person.';
$_toolhelp_insert_parent = 'Relate an existing person as the %s of this person.';
$_toolhelp_edit_parent = 'Edit the relationship between person(%d) and the %s shown here.';
$_toolhelp_delete_parent = 'Delete the relationship between person(%d) and the %s shown here.';
$_toolhelp_untyped_source = 'This source is in the alert style because you haven&apos;t defined a TYPE for this source. It&apos;s recommended you edit the source and change its type to TRANSCRIPT (or whatever is appropriate).';
$_toolhelp_edituse_source = 'View/Edit/Use the source (%d) referred to in this citation.';
$_toolhelp_editdel_event = 'Edit/delete this event (%d) for this person/participant (%d).';
$_toolhelp_editdel_event_witness = 'Edit/delete this event (%d) for a witness note/ALTNAMEUSAGE???.';
$_To_top = 'To top';
$_Toponym = 'Toponym';
$_Type = 'Type';
$_Unknown = 'Unknown';
$_Unknown_spouse = 'Unknown spouse';
$_unidentified = 'unidentified';
$_Up = 'Up';
$_underlying_events = 'underlying events';
$_unregistered = 'unregistered';
$_Unused = 'Unused';
$_use = 'use';
$_Use_source_for_birth_event = 'Use source(s) for birth event';
$_User_details = 'User details';
$_User_settings = 'User settings';
$_view = 'view';
$_View_source = 'View source';
$_Wife = 'Wife';
$_With = 'With person'; // sms 29 July 2011
$_with = 'with';
$_Year = 'Year';
$_Yes = 'Yes';

// help text in forms 
$_help['default_template'] = 'No help for field:';
$_help['event_note'] = "Optional notes for this event";
$_help['source_text'] = "Text of the source";
$_help['source_id'] = "Number which identifies this source";
$_help['tag_type'] = "This determines the number of participants who can be associated with an event of this type.";
$_help['tag_group'] = "Broad grouping or class of similar events to which this event belongs.";
$_help['gedcom_tag'] = "For future use in import/export to GEDCOM.";
$_help['tag_name'] = "Name of the event.";
$_help['tag_label'] = "IGNORE: Check with Leif -- tag_label may be redundant?";
$_help['tag_id'] = "Type of event. Events provide a linkage between sources and persons.";
// ########### add more: $_help['

?>
