<?php
/* php source dbid to xml recid mappings (generated by http://www.fu.org) */
$XMAPHi     = 900000000; # src dbids above this are special, map to xml rectypes/ids
$XMAPHi_div = 10000000; # ?
$XMAPLo     = 10000000; # src dbids above this are special, map to xml rectypes/ids
$XMAPLo_div = 1000000; # ?

/* entries with the 'hi' attribute exceed $XMAPHi; those without exceed $XMAPLo */
$SOURCEMAP = array(
     12 => array( "id" => "ccc", "eventtype" => '', "persontype" => 'convict', "lz" => '', "desc" => 'Convicts Contrib', "db" => 'ccc_mediaflux', "xq" => '//person[@id="ID"]', "hi" => '' ),
     16 => array( "id" => "ai", "eventtype" => '', "persontype" => 'convict', "lz" => '5', "desc" => 'Taho Index', "db" => 'raw_ai', "xq" => '//ai[@id="ID"]', "hi" => '' ),
     18 => array( "id" => "dlm", "eventtype" => '', "persontype" => 'convict_M', "lz" => '', "desc" => 'Con18', "db" => 'raw_dlm', "xq" => '//dlm[@id="ID"]', "hi" => '' ),
     19 => array( "id" => "dlf", "eventtype" => '', "persontype" => 'convict_F', "lz" => '', "desc" => 'Con19', "db" => 'raw_dlf', "xq" => '//dlf[@id="ID"]', "hi" => '' ),
     23 => array( "id" => "c23a", "eventtype" => '', "persontype" => 'convict_M', "lz" => '', "desc" => 'Con23', "db" => 'raw_c23a', "xq" => '//c23a[@id="ID"]', "hi" => '' ),
     31 => array( "id" => "c31a", "eventtype" => '', "persontype" => 'convict_M', "lz" => '', "desc" => 'Con31', "db" => 'raw_c31a', "xq" => '//c31a[@id="ID"]', "hi" => '' ),
     33 => array( "id" => "c33a", "eventtype" => '', "persontype" => 'convict_M', "lz" => '', "desc" => 'Con33', "db" => 'raw_c33a', "xq" => '//c33a[@id="ID"]', "hi" => '' ),
     40 => array( "id" => "c40a", "eventtype" => '', "persontype" => 'convict_F', "lz" => '', "desc" => 'Con40', "db" => 'raw_c40a', "xq" => '//c40a[@id="ID"]', "hi" => '' ),
     52 => array( "id" => "pm", "eventtype" => '', "persontype" => 'person', "lz" => '', "desc" => 'Permission to marry index (Taho)', "db" => 'norm_pm', "xq" => '//pm[@id="ID"]', "hi" => '' ),
     155 => array( "id" => "om", "eventtype" => '', "persontype" => 'convict_M', "lz" => '', "desc" => 'Oxley Male', "db" => 'raw_om', "xq" => '//om[@id="ID"]', "hi" => '' ),
     156 => array( "id" => "of", "eventtype" => '', "persontype" => 'convict_F', "lz" => '', "desc" => 'Oxley Female', "db" => 'raw_of', "xq" => '//of[@id="ID"]', "hi" => '' ),
     157 => array( "id" => "di", "eventtype" => '', "persontype" => 'person', "lz" => '', "desc" => 'Departures from TAS', "db" => 'raw_di', "xq" => '//di[@id="ID"]', "hi" => '' ),
     158 => array( "id" => "dcm", "eventtype" => '', "persontype" => 'convict_M', "lz" => '', "desc" => 'Deaths Male', "db" => 'raw_dcm', "xq" => '//dcm[@id="ID"]', "hi" => '' ),
     159 => array( "id" => "dcf", "eventtype" => '', "persontype" => 'convict_F', "lz" => '', "desc" => 'Deaths Female', "db" => 'raw_dcf', "xq" => '//dcf[@id="ID"]', "hi" => '' ),
     210 => array( "id" => "ff", "eventtype" => '', "persontype" => 'convict_F', "lz" => '', "desc" => 'FCRC convict id (female)', "db" => 'raw_ff', "xq" => '//ff[@id="ID"]', "hi" => '' ),
     220 => array( "id" => "if", "eventtype" => '', "persontype" => 'wwidigger', "lz" => '', "desc" => 'WWI Diggers', "db" => 'raw_if', "xq" => '//if[@id="ID"]', "hi" => '' ),
     510 => array( "id" => "kgb", "eventtype" => '', "persontype" => 'tasborn', "lz" => '', "desc" => 'TAS Birth Regn', "db" => 'norm_kgb', "xq" => '//source[@ysid="ID"]', "hi" => '' ),
     520 => array( "id" => "kgm", "eventtype" => '', "persontype" => 'person', "lz" => '', "desc" => 'TAS Marriage Regn', "db" => 'norm_kgm', "xq" => '//source[@ysid="ID"]', "hi" => '' ),
     530 => array( "id" => "kgd", "eventtype" => '', "persontype" => 'person', "lz" => '', "desc" => 'TAS Death Regn', "db" => 'norm_kgd', "xq" => '//source[@ysid="ID"]', "hi" => '' ),
     100 => array( "id" => "branch.vdlbdm", "eventtype" => '', "persontype" => '', "lz" => '', "desc" => 'TAS BDM Registrations', "db" => '', "xq" => '', "hi" => '1' ),
     101 => array( "id" => "branch.kgb", "eventtype" => 'BIRT', "persontype" => '', "lz" => '', "desc" => 'TAS Birth Regn', "db" => 'vdlbdm/kgb_RegDistrictYear.xml', "xq" => '//item[@dbid="ID"]', "hi" => '1' ),
     102 => array( "id" => "branch.kgm", "eventtype" => 'MARR', "persontype" => '', "lz" => '', "desc" => 'TAS Marriage Regn', "db" => 'vdlbdm/kgm_RegDistrictYear.xml', "xq" => '//item[@dbid="ID"]', "hi" => '1' ),
     103 => array( "id" => "branch.kgd", "eventtype" => 'DEAT', "persontype" => '', "lz" => '', "desc" => 'TAS Death Regn', "db" => 'vdlbdm/kgd_RegDistrictYear.xml', "xq" => '//item[@dbid="ID"]', "hi" => '1' ),
     9 => array( "id" => "ert", "eventtype" => '', "persontype" => 'ert', "lz" => '8', "desc" => 'Tas born WW1 enlistee', "db" => 'raw_ert', "xq" => '//ert[@id="ID"]', "hi" => '1' ));

$PEOPLEMAP = array(
     13 => array( "role" => "Sp", "participantInSource" => 12, "desc" => 'Spouse' ),
     14 => array( "role" => "Ch", "participantInSource" => 12, "desc" => 'Child' ),
     15 => array( "role" => "Di", "participantInSource" => 12, "desc" => 'AifDescendant' ),
     17 => array( "role" => "Ch", "participantInSource" => 16, "desc" => 'Children' ),
     220 => array( "role" => "DiI", "participantInSource" => 220, "desc" => 'DiggerWWI' ),
     510 => array( "role" => "Ba", "participantInSource" => 510, "desc" => 'Baby' ),
     511 => array( "role" => "Fa", "participantInSource" => 510, "desc" => 'Father' ),
     512 => array( "role" => "Mo", "participantInSource" => 510, "desc" => 'Mother' ),
     519 => array( "role" => "In", "participantInSource" => 510, "desc" => 'Informant' ),
     521 => array( "role" => "Hu", "participantInSource" => 520, "desc" => 'Husband' ),
     522 => array( "role" => "Wi", "participantInSource" => 520, "desc" => 'Wife' ),
     523 => array( "role" => "wt", "participantInSource" => 520, "desc" => 'Witness' ),
     530 => array( "role" => "De", "participantInSource" => 530, "desc" => 'Deceased' ));
?>
