#!/bin/bash

# Deployed copy of ap20-ands/src/usr-local-bin/ap20init.sh
# www-data can run this once only as root to set up web security
. /etc/environment

WEBROOT=$AP20_WEBROOT

echo "##== $0"

DIV_S='<div class="boxquote">'
DIV_E='</div>'
DELIM="======================================="
echo ""
echo "$DELIM Preconfigured envt variables:"
echo ""
echo "-- FASHOST     [$FASHOST] # Ignore. Used for Founders And Survivors project."
echo "-- AP20_HOME   [$AP20_HOME] # Location of non-web application components"
echo "-- AP20_WEBROOT[$AP20_WEBROOT] # Location of web application components"

echo ""
echo "$DELIM Configuring $WEBROOT/index.html"
echo ""
ls -la $WEBROOT/index.html

echo ""
echo "-- changing to index-app.html"
cd $WEBROOT
if [ -L index.html ]; then
   echo ".. index.html is symlink"
   IDX=`readlink -f index.html`
   ls -la index.html
   if [ "$IDX" == "$WEBROOT/index-local.html" ]; then
      echo ".. retaining symlink to index-local.html"
   else
      echo ".. IDX[$IDX] removing symlink"
      sudo rm index.html
      ln -s index-app.html index.html
   fi
else
   if [ -f index.html ]; then
      echo ".. index.html exists is file, saving as index-prev.html"
      sudo mv index.html index-prev.html
      ln -s index-app.html index.html
   else
      echo ".. index.html does not exist, can proceed"
      ln -s index-app.html index.html
   fi
fi

ls -la $WEBROOT/index.html
echo ""
echo "$DELIM /srv/.first contains credentials:"
ls -la /srv/.first
CREDENTIALS=`cat /srv/.first`
echo $DIV_S$CREDENTIALS$DIV_E

echo ""
echo "$DELIM Create apache password file:"
HTPASSFILE="/var/webwork/htpasswd"
/usr/bin/htpasswd -b -c $HTPASSFILE $CREDENTIALS
rc=$?
echo "-- rc[$rc]:"
ls -la $HTPASSFILE

if [[ $rc != 0 ]]; then
   echo "## ABNORMAL EOJ"
   exit 9
fi

echo "-- success. "

REALM="ap20img admin access"
echo ""
echo "$DELIM Now configuring .htaccess files realm[$REALM]..."
echo ""

# these locations are relative to WEBROOT
for DIR in documentation test ap20/khrd-dev
do
   D=$WEBROOT/$DIR
   FILE=$D/.htaccess
   echo ""
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   echo "+ protecting location \$WEBROOT/$DIR"
   echo "++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
   echo ""
   ACTION="Created."
   if [[ -f $FILE ]]; then
      ACTION="Retained."
   else
      echo "##---- $FILE generated by $0"        > $FILE
      echo "Order Allow,Deny"                   >> $FILE
      echo "Allow from all"                     >> $FILE
      echo "AuthUserFile $HTPASSFILE"           >> $FILE
      echo "AuthType Basic"                     >> $FILE
      echo "AuthName \"$REALM\""                >> $FILE
      echo "Require valid-user"                 >> $FILE
      echo ""
   fi
   echo "-- $ACTION $FILE contains:$DIV_S"
   cat $FILE
   echo $DIV_E
done

exit 0
